version: 1
validation: sovereign
accounts: 
- name: WhiteTruffle
  coins:
  - 10000000000koikrystal
  - 105000000bitpearl
- name: Tectract
  coins:
  - 10000000000koikrystal
  - 105000000bitpearl
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: Tectract
  coins:
  - 1000000000koikrystal
validators:
- name: WhiteTruffle
  bonded: 1000000000bitpearl
- name: 
  bonded: 1000000000bitpearl
